"""init tables

Revision ID: aa0ba1477973
Revises: 
Create Date: 2026-01-26 13:38:27.221828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa0ba1477973'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_run',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('draft_id', sa.String(length=128), nullable=False),
    sa.Column('prev_run_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_esg_run_draft_id'), 'esg_run', ['draft_id'], unique=False)
    op.create_table('esg_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('ext', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['esg_run.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_file_run_id'), 'esg_file', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esg_file_run_id'), table_name='esg_file')
    op.drop_table('esg_file')
    op.drop_index(op.f('ix_esg_run_draft_id'), table_name='esg_run')
    op.drop_table('esg_run')
    # ### end Alembic commands ###
